from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('home', views.home),
    path('navbar', views.navbar),
    path('directions', views.directions),
    path('cart', views.cart),
    path('checkout', views.checkout),
    path('login', views.login),
    path('news', views.news),
    path('events', views.events),
    path('about_us', views.about_us),
    path('contact_us', views.contact_us),
    path('contact_us/contact_send', views.contact_send),
    path('products/<int:product_id>', views.product_detail),
    path('products/assign_to_sale', views.assign_to_sale),
    path('products/add_to_cart', views.add_to_cart),
    path('products/delete_product/<int:id>', views.delete_product),
    path('products/edit_product/<int:product_id>', views.edit_product),
    path('products/edit_product_table', views.edit_product_table),
    path('product/admin_product_detail/<int:product_id>', views.admin_product_detail),
    path('products/update_quantity/<int:id>', views.update_quantity),
    path('products/remove_from_cart/<int:id>', views.remove_order_item),
    path('products/empty_cart', views.empty_cart),
    path('category/<int:id>', views.show_category),
    path('category/<int:id>/<str:sort>', views.sort_category),
    path('create_sale', views.create_sale),
    path('create_product', views.create_product),
    path('create_category', views.create_category),
    path('create_brand', views.create_brand),
    path('users/register', views.register_user),
    path('users/login', views.log_in),
    path('users/logout', views.log_out),
    path('users/delete_user/<int:user_id>', views.delete_user),
    path('admin/home', views.admin_home),
    path('admin/user_manager/<int:id>', views.admin_user_manager),
    path('admin/update_user/<int:id>', views.admin_update_user),
    path('admin/news', views.admin_news),
    path('admin/news/create_article', views.create_article),
    path('admin/update_sale', views.update_sale),
]