# Generated by Django 2.2 on 2020-11-19 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0002_product_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='admin',
        ),
    ]
