# Generated by Django 2.2 on 2020-11-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0004_auto_20201115_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='productImages'),
        ),
    ]
